tuple_ = (5, 2, 24, 3, 1, 6, 7)
print(sorted(tuple_))
sorted_ = tuple(sorted(tuple_))
print('Sorted Tuple :', sorted_)  
print(type(sorted_))  
tuple_ = (5, 2, 24, 3, 1, 6, 7)  
sorted_ = tuple(sorted(tuple_, reverse=True))  
print('Sorted Tuple :', sorted_)  
print(type(sorted_))  
